# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

os:
  # I usually use lazygit embedded in nvim. For this, I use
  # https://github.com/willothy/flatten.nvim to simplify the setup without the
  # need for external applications.

  # edit: "nvim {{filename}}"
  # editAtLine: "nvim +{{line}} {{filename}}"
  # editAtLineAndWait: "nvim +{{line}} {{filename}}"

  # Create pull request command opens a URL with incorrect escaping #3064
  # https://github.com/jesseduffield/lazygit/issues/3064
  openLink: open -n "$(echo {{link}} | sed 's/%3E/>/g' | sed 's/%2F/\//g' | sed
    s/%27/\'/g )"

promptToReturnFromSubprocess: false

notARepository: "quit"

# https://github.com/catppuccin/lazygit/blob/main/themes-mergable/macchiato/pink.yml
gui:
  commitHashLength: 0
  skipRewordInEditorWarning: true
  nerdFontsVersion: "3"
  scrollHeight: 10
  mainPanelSplitMode: vertical
  showDivergenceFromBaseBranch: arrowAndNumber
  theme:
    activeBorderColor:
      - "#f5bde6"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#f5bde6"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"

git:
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --paging=never
