enable_nightly_info = true
enable_release_build = true
downloads_location = "$Xdirs[data]/bob"
installation_location = "$Xdirs[bin]"
version_sync_file_location = "$Xdirs[conf]/nvim/.version"
rollback_limit = 5
github_mirror = "https://github.com"
